- name: Create Nginx configuration directory on host if it doesn't exist
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Template Nginx configuration file on host
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx Container

- name: Run Nginx Container
  community.docker.docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_image }}"
    state: started
    recreate: true
    published_ports:
      - 80:80
    networks:
      - name: "{{ backend_network }}"
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
