- name: Clean apt cache
  ansible.builtin.shell: |
    rm -rf /var/cache/apt/*
    apt-get clean
    apt-get update
  failed_when: result.rc not in [0, 100]
  register: result

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update package index
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - python3-psycopg2

- name: Create Docker network if it does not exist
  community.docker.docker_network:
    name: "{{ vm_network }}"
    state: present
