- name: Setup server
  hosts: development
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    username: galihhhp
  vars_files:
    - vault.yaml
  tasks:
    - name: Install python env
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - python3
        - python3-pip
        - python3-passlib

    - name: Hash password using passlib
      ansible.builtin.shell: |
        python3 -c "from passlib.hash import sha512_crypt; print(sha512_crypt.hash('{{ password }}'))"
      register: hashed_password

    - name: Manage user account '{{ username }}'
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        home: "/home/{{ username }}"
        password: "{{ hashed_password.stdout }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_type: "rsa"
        ssh_key_file: ".ssh/id_rsa"
        ssh_key_comment: "{{ ansible_fqdn }}"
    - name: Ensure PasswordAuthentication is set to no
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
