- name: Setup application
  hosts: development
  vars:
    image: galihhhp/simple-fastify
    container_name: fastify
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - nodejs
        - npm

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update package index
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Pull an image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull
        pull:
          platform: amd64

    - name: Check if Docker Container exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        state: present
      register: container_check

    - name: Create Container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: present
        image: "{{ image }}"
        published_ports:
          - 4000:4000
        command: sleep infinity
      when: not container_check.changed

    - name: Start container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        state: started
