- name: Install python env
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - python3
    - python3-pip
    - python3-passlib

- name: Hash password using passlib
  ansible.builtin.shell: |
    python3 -c "from passlib.hash import sha512_crypt; print(sha512_crypt.hash('{{ password }}'))"
  register: hashed_password

- name: Manage user account '{{ user_setup_username }}'
  ansible.builtin.user:
    name: "{{ user_setup_username }}"
    state: present
    home: "/home/{{ user_setup_username }}"
    password: "{{ hashed_password.stdout }}"
    generate_ssh_key: true
    ssh_key_bits: 2048
    ssh_key_type: "rsa"
    ssh_key_file: ".ssh/id_rsa"
    ssh_key_comment: "{{ ansible_fqdn }}"
