- name: Install packages
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present
    update_cache: true

- name: Pull PostgreSQL image
  community.docker.docker_image:
    name: "{{ postgresql_image }}"
    source: pull
    pull:
      platform: amd64

- name: Create a volume
  community.docker.docker_volume:
    name: "{{ postgresql_volume }}"

- name: Run PostgreSQL container
  community.docker.docker_container:
    name: "{{ postgresql_container_name }}"
    image: "{{ postgresql_image }}"
    state: started
    published_ports:
      - "{{ postgresql_internal_ip }}:{{ postgresql_port }}:5432"
    env:
      POSTGRES_USER: "{{ postgresql_user }}"
      POSTGRES_PASSWORD: "{{ password }}"
      POSTGRES_DB: "{{ postgresql_name }}"
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    volumes:
      - "{{ postgresql_volume }}:/var/lib/postgresql/data"
    networks:
      - name: "{{ vm_network }}"
  notify:
    - PostgreSQL Setup Complete
    - Create database if it does not exist
    - Create task table
