- name: Setup application
  hosts: backend
  become: true
  vars:
    backend_image: galihhhp/fastify:3.0
    nginx_image: nginx
    container_name: fastify
    nginx_container_name: nginx
    vm_network: vm_network
    postgresql_port: "5432"
    ansible_hostname: backend
    deployment_env: development
  vars_files:
    - ../vault.yaml
  roles:
    - filebeat
    - app_deployment
    - nginx
