- name: Setup application
  hosts: backend
  become: true
  vars:
    backend_image: galihhhp/fastify:1.1.0
    nginx_image: nginx
    container_name: fastify
    nginx_container_name: nginx
    backend_network: backend-network
    postgresql_port: "5432"
  vars_files:
    - ../vault.yaml
  roles:
    - app_deployment
    - nginx
