- name: Setup server
  hosts: backend
  become: true
  vars:
    vm_network: vm_network
  vars_files:
    - ../vault.yaml
  roles:
    - common_tasks
    - app_package
    - user_management
    - app_ufw
    - common_docker
