- name: Setup database server
  hosts: database
  become: true
  vars:
    postgresql_container_name: postgresql
    postgresql_image: postgres:17.5-alpine
    postgres_user: galihhhp
    postgres_volume: pg_data
    db_name: tasks
  vars_files:
    - ../vault.yaml
  roles:
    - timezone_config
    - locale_config
    - postgresql
