- name: Ensure PasswordAuthentication is set to no
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
- name: Restart SSH service
  ansible.builtin.service:
    name: sshd
    state: restarted
