- name: Pull an image
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
    pull:
      platform: amd64
  loop:
    - "{{ backend_image }}"
    - "{{ nginx_image }}"

- name: Create a network
  community.docker.docker_network:
    name: "{{ backend_network }}"
    state: present

- name: Run App Container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "{{ backend_image }}"
    state: started
    recreate: true
    networks:
      - name: "{{ backend_network }}"
        aliases:
          - "{{ container_name }}"
    env:
      DB_HOST: "{{ postgresql_host }}"
      DB_PORT: "{{ postgresql_port }}"
      DB_USER: "{{ postgresql_user }}"
      DB_PASSWORD: "{{ password }}"
      DB_NAME: "{{ postgresql_name }}"
