- name: PostgreSQL Setup Complete
  community.docker.docker_container_exec:
    container: "{{ postgresql_container_name }}"
    command: pg_isready -U {{ postgresql_user }} -d {{ postgresql_name }}
  register: pg_ready
  until: pg_ready.rc == 0
  retries: 30
  delay: 6

- name: Create database if it does not exist
  community.postgresql.postgresql_db:
    name: "{{ postgresql_name }}"
    state: present
    login_user: "{{ postgresql_user }}"
    login_password: "{{ password }}"
    login_host: "{{ postgresql_internal_ip }}"
    login_port: "{{ postgresql_port }}"

- name: Create task table
  community.postgresql.postgresql_query:
    login_db: "{{ postgresql_name }}"
    query: |
      CREATE TABLE IF NOT EXISTS test_table (
        id bigserial primary key,
        task text
      );
    login_user: "{{ postgresql_user }}"
    login_password: "{{ password }}"
    login_host: "{{ postgresql_internal_ip }}"
    login_port: "{{ postgresql_port }}"
