name: Ansible CI/CD Deploy

on:
  push:
    branches: [main]
    paths:
      - "playbooks/**"
      - ".github/workflows/ansible-deploy.yml"
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Ansible & Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Create inventory directory
        run: mkdir -p inventory

      - name: Create Ansible inventory file
        run: |
          cat > inventory/hosts.ini << EOF
          ${{ secrets.ANSIBLE_INVENTORY }}
          EOF
          chmod 600 inventory/hosts.ini

      - name: Create Vault Password File
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > vault_pass.txt
          chmod 600 vault_pass.txt

      - name: Syntax Check
        run: |
          ansible-playbook playbooks/elk.yaml --syntax-check --vault-password-file vault_pass.txt
          ansible-playbook playbooks/app_setup.yaml --syntax-check --vault-password-file vault_pass.txt
          ansible-playbook playbooks/app.yaml --syntax-check --vault-password-file vault_pass.txt
          ansible-playbook playbooks/database.yaml --syntax-check --vault-password-file vault_pass.txt

      - name: Deploy with Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/elk.yaml
          directory: ./
          key: ${{ secrets.DEV_SSH_KEY }}
          inventory: inventory/hosts.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Deploy App Setup
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/app_setup.yaml
          directory: ./
          key: ${{ secrets.DEV_SSH_KEY }}
          inventory: inventory/hosts.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Deploy App
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/app.yaml
          directory: ./
          key: ${{ secrets.DEV_SSH_KEY }}
          inventory: inventory/hosts.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Deploy Database
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/database.yaml
          directory: ./
          key: ${{ secrets.DEV_SSH_KEY }}
          inventory: inventory/hosts.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Cleanup
        if: always()
        run: |
          rm -f vault_pass.txt
          rm -f inventory/hosts.ini
